# Generated by Django 4.2.8 on 2023-12-24 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entry',
            new_name='Bntry',
        ),
    ]
